### PR TITLE
Meilisearch

### PR DESCRIPTION
**Pull request by huacnlee**

### CODE REVIEW

**Comment by huacnlee** [comment]
Close #892

**Comment by tpayet** [comment]
Hello, thank you for trying out MeiliSearch :)
I just saw that you reverted the commit and came back to Elasticsearch in less than 6 jours. In order to better understand developers usage of Elasticsearch and MeilISearch, may I ask why? 😬

Have a nice day :)

**Comment by huacnlee** [comment]
> Hello, thank you for trying out MeiliSearch :)
> 
> I just saw that you reverted the commit and came back to Elasticsearch in less than 6 jours. In order to better understand developers usage of Elasticsearch and MeilISearch, may I ask why? 😬
> 
> 
> 
> Have a nice day :)

Memory leaks, too fast leak.

And it also not supports with Chinese contents search will

**Comment by huacnlee** [comment]
And I was used MeiliSearch 0.9.1 version build from master branch.

**Comment by tpayet** [comment]
Thank you, we will investigate in possible memory leaks.
We are also working on [improving the tokenizer.](https://github.com/meilisearch/MeiliSearch/issues/560)

Have a nice day!

**Comment by huacnlee** [comment]
I will keep watching yours change, and I am happy to try it again.

**Pull request merged**
